import * as fs from 'fs/promises';
import * as path from 'path';
import {ProjectContext} from '../types/index.js';
import {formatImportGraphMermaid} from '../detectors/imports.js';
import {getFullContext} from './getFullContext.js';

const DOCS_DIR = '.repo-context';

/**
 * Generate auto-docs from ProjectContext into .repo-context/ directory.
 * These files are read naturally by the AI — 0 MCP token cost.
 */
export async function generateDocs(projectRoot: string): Promise<void> {
	const context = await getFullContext(projectRoot, true);
	const docsPath = path.join(projectRoot, DOCS_DIR);

	// Ensure directory exists
	await fs.mkdir(docsPath, {recursive: true});

	// Generate all docs in parallel
	await Promise.all([
		writeArchitecture(docsPath, context),
		writeComponents(docsPath, context),
		writeModels(docsPath, context),
		writeImports(docsPath, context),
		writeStatus(docsPath, context),
	]);

	// Add .repo-context/ to .gitignore if not already there
	await ensureGitignore(projectRoot);

	console.error(`[repo-context] Auto-docs generated in ${DOCS_DIR}/`);
}

// ─── ARCHITECTURE.md ───

async function writeArchitecture(
	docsPath: string,
	ctx: ProjectContext
): Promise<void> {
	const lines: string[] = [
		`# ${ctx.name} — Architecture`,
		`> Auto-generated by repo-context-mcp. Do not edit manually.`,
		'',
		`## Stack`,
		`- **Language:** ${ctx.stack.primaryLanguage}`,
	];

	if (ctx.stack.frameworks.length > 0) {
		lines.push(
			`- **Frameworks:** ${ctx.stack.frameworks.map((f) => f.name).join(', ')}`
		);
	}
	if (ctx.stack.packageManager) {
		lines.push(`- **Package Manager:** ${ctx.stack.packageManager}`);
	}
	if (ctx.stack.runtime) {
		lines.push(`- **Runtime:** ${ctx.stack.runtime}`);
	}

	// Dependencies
	const prodDeps = ctx.stack.dependencies.filter((d) => !d.dev);
	const devDeps = ctx.stack.dependencies.filter((d) => d.dev);

	if (prodDeps.length > 0) {
		lines.push('', '## Dependencies');
		for (const d of prodDeps.slice(0, 15)) {
			lines.push(`- ${d.name} ${d.version}`);
		}
		if (prodDeps.length > 15) {
			lines.push(`- ...and ${prodDeps.length - 15} more`);
		}
	}

	if (devDeps.length > 0) {
		lines.push('', '## Dev Dependencies');
		for (const d of devDeps.slice(0, 10)) {
			lines.push(`- ${d.name} ${d.version}`);
		}
		if (devDeps.length > 10) {
			lines.push(`- ...and ${devDeps.length - 10} more`);
		}
	}

	// Architecture pattern
	lines.push('', '## Architecture Pattern');
	lines.push(`- **Pattern:** ${ctx.architecture.pattern}`);
	lines.push(`- ${ctx.architecture.description}`);
	if (ctx.architecture.layers.length > 0) {
		lines.push(`- **Layers:** ${ctx.architecture.layers.join(' → ')}`);
	}

	lines.push('', `*Updated: ${ctx.analyzedAt}*`);
	await fs.writeFile(
		path.join(docsPath, 'ARCHITECTURE.md'),
		lines.join('\n'),
		'utf-8'
	);
}

// ─── COMPONENTS.md ───

async function writeComponents(
	docsPath: string,
	ctx: ProjectContext
): Promise<void> {
	const lines: string[] = [
		`# ${ctx.name} — Project Structure`,
		`> Auto-generated by repo-context-mcp. Do not edit manually.`,
		'',
	];

	// Entry points
	if (ctx.structure.entryPoints.length > 0) {
		lines.push('## Entry Points');
		for (const entry of ctx.structure.entryPoints) {
			lines.push(`- \`${entry}\``);
		}
		lines.push('');
	}

	// Folders
	lines.push('## Folders');
	for (const folder of ctx.structure.folders) {
		const largest = folder.largestFile
			? ` — ⚠ largest: \`${folder.largestFile.name}\` (${folder.largestFile.lines}L)`
			: '';
		lines.push(
			`- **${folder.path}/** (${folder.fileCount} files) — ${folder.description}${largest}`
		);
		if (folder.mainFiles && folder.mainFiles.length > 0) {
			lines.push(
				`  - Main: ${folder.mainFiles.map((f) => `\`${f}\``).join(', ')}`
			);
		}
	}

	// Config files
	if (ctx.structure.configFiles.length > 0) {
		lines.push('', '## Config Files');
		lines.push(ctx.structure.configFiles.map((f) => `\`${f}\``).join(', '));
	}

	// Hot files
	if (ctx.hotFiles && ctx.hotFiles.files.length > 0) {
		lines.push('', `## ⚠ Hot Files (${ctx.hotFiles.files.length})`);
		lines.push(
			`*Thresholds: >${ctx.hotFiles.thresholds.lines} lines, >${ctx.hotFiles.thresholds.imports} imports*`
		);
		lines.push('');
		lines.push('| File | Lines | Reason | Details |');
		lines.push('|------|-------|--------|---------|');
		for (const hf of ctx.hotFiles.files) {
			const details: string[] = [];
			if (hf.imports) details.push(`${hf.imports} imports`);
			if (hf.exports) details.push(`${hf.exports} exports`);
			if (hf.todoCount) details.push(`${hf.todoCount} TODOs`);
			lines.push(
				`| \`${hf.file}\` | ${hf.lines} | ${hf.reason} | ${
					details.join(', ') || '-'
				} |`
			);
		}
	}

	// Endpoints
	if (ctx.endpoints && ctx.endpoints.endpoints.length > 0) {
		lines.push('', `## API Endpoints (${ctx.endpoints.endpoints.length})`);
		lines.push('');
		lines.push('| Method | Path | File |');
		lines.push('|--------|------|------|');
		for (const ep of ctx.endpoints.endpoints.slice(0, 30)) {
			lines.push(`| ${ep.method} | \`${ep.path}\` | ${ep.file}:${ep.line} |`);
		}
		if (ctx.endpoints.endpoints.length > 30) {
			lines.push(`\n...and ${ctx.endpoints.endpoints.length - 30} more endpoints`);
		}
	}

	lines.push('', `*Updated: ${ctx.analyzedAt}*`);
	await fs.writeFile(
		path.join(docsPath, 'COMPONENTS.md'),
		lines.join('\n'),
		'utf-8'
	);
}

// ─── MODELS.md ───

async function writeModels(
	docsPath: string,
	ctx: ProjectContext
): Promise<void> {
	const lines: string[] = [
		`# ${ctx.name} — Data Models`,
		`> Auto-generated by repo-context-mcp. Do not edit manually.`,
		'',
	];

	if (!ctx.models || ctx.models.models.length === 0) {
		lines.push('No data models detected.');
	} else {
		if (ctx.models.ormUsed) {
			lines.push(`**ORM:** ${ctx.models.ormUsed}`);
			lines.push('');
		}

		for (const model of ctx.models.models) {
			lines.push(`### ${model.name} (${model.type})`);
			lines.push(`*File: ${model.file}:${model.line}*`);
			lines.push('');
			if (model.fields.length > 0) {
				lines.push('| Field | Type | Required |');
				lines.push('|-------|------|----------|');
				for (const field of model.fields) {
					lines.push(
						`| ${field.name} | ${field.type || '-'} | ${
							field.required ? '✅' : '❌'
						} |`
					);
				}
			}
			lines.push('');
		}
	}

	lines.push(`*Updated: ${ctx.analyzedAt}*`);
	await fs.writeFile(
		path.join(docsPath, 'MODELS.md'),
		lines.join('\n'),
		'utf-8'
	);
}

// ─── IMPORTS.md ───

async function writeImports(
	docsPath: string,
	ctx: ProjectContext
): Promise<void> {
	const lines: string[] = [
		`# ${ctx.name} — Import Graph`,
		`> Auto-generated by repo-context-mcp. Do not edit manually.`,
		'',
	];

	if (!ctx.importGraph || ctx.importGraph.nodes.length === 0) {
		lines.push('No significant import graph detected.');
	} else {
		// Hub files
		if (ctx.importGraph.mostImported.length > 0) {
			lines.push('## 🔗 Hub Files (most imported)');
			for (const hub of ctx.importGraph.mostImported) {
				const node = ctx.importGraph.nodes.find((n) => n.file === hub);
				lines.push(`- **${hub}** — imported by ${node?.importedBy || '?'} files`);
			}
			lines.push('');
		}

		// Orphan files
		if (ctx.importGraph.orphans.length > 0) {
			lines.push('## 🔴 Orphan Files (not imported by anyone)');
			for (const orphan of ctx.importGraph.orphans) {
				lines.push(`- ${orphan}`);
			}
			lines.push('');
		}

		// Significant nodes
		lines.push('## Dependency Details');
		lines.push('');
		lines.push('| File | Imported By | Imports |');
		lines.push('|------|-------------|---------|');
		for (const node of ctx.importGraph.nodes) {
			lines.push(
				`| \`${node.file}\` | ←${node.importedBy} | ${node.imports
					.slice(0, 5)
					.join(', ')}${node.imports.length > 5 ? '...' : ''} |`
			);
		}

		// Mermaid diagram
		lines.push('', '## Visual Graph');
		lines.push('');
		lines.push('```mermaid');
		lines.push(formatImportGraphMermaid(ctx.importGraph));
		lines.push('```');
	}

	lines.push('', `*Updated: ${ctx.analyzedAt}*`);
	await fs.writeFile(
		path.join(docsPath, 'IMPORTS.md'),
		lines.join('\n'),
		'utf-8'
	);
}

// ─── STATUS.md ───

async function writeStatus(
	docsPath: string,
	ctx: ProjectContext
): Promise<void> {
	const lines: string[] = [
		`# ${ctx.name} — Project Status`,
		`> Auto-generated by repo-context-mcp. Do not edit manually.`,
		'',
		'## Infrastructure',
		`- **Tests:** ${ctx.status.tests.testFiles} test files${
			ctx.status.tests.framework ? ` (${ctx.status.tests.framework})` : ''
		}`,
		`- **Docker:** ${ctx.status.hasDocker ? 'Yes' : 'No'}`,
		`- **CI/CD:** ${ctx.status.hasCI ? `Yes (${ctx.status.ciPlatform})` : 'No'}`,
		`- **Documentation:** ${ctx.status.hasDocumentation ? 'Yes' : 'No'}`,
	];

	// TODOs
	if (ctx.status.todos.length > 0) {
		lines.push('', `## TODOs (${ctx.status.todos.length})`);
		for (const todo of ctx.status.todos.slice(0, 15)) {
			const priority =
				todo.priority === 'high' ? '🔴' : todo.priority === 'medium' ? '🟡' : '⚪';
			lines.push(`- ${priority} ${todo.text} — \`${todo.file}:${todo.line}\``);
		}
		if (ctx.status.todos.length > 15) {
			lines.push(`- ...and ${ctx.status.todos.length - 15} more`);
		}
	}

	// Annotations
	if (ctx.annotations) {
		if (ctx.annotations.businessRules.length > 0) {
			lines.push('', '## 📋 Business Rules');
			for (const rule of ctx.annotations.businessRules) {
				lines.push(`- ${rule}`);
			}
		}
		if (ctx.annotations.gotchas.length > 0) {
			lines.push('', '## ⚠ Gotchas');
			for (const g of ctx.annotations.gotchas) {
				lines.push(`- ${g}`);
			}
		}
		if (ctx.annotations.warnings.length > 0) {
			lines.push('', '## 🔴 Warnings');
			for (const w of ctx.annotations.warnings) {
				lines.push(`- ${w}`);
			}
		}
	}

	lines.push('', `*Updated: ${ctx.analyzedAt}*`);
	await fs.writeFile(
		path.join(docsPath, 'STATUS.md'),
		lines.join('\n'),
		'utf-8'
	);
}

// ─── .gitignore helper ───

async function ensureGitignore(projectRoot: string): Promise<void> {
	const gitignorePath = path.join(projectRoot, '.gitignore');
	const dirEntry = `${DOCS_DIR}/`;
	try {
		const content = await fs.readFile(gitignorePath, 'utf-8');
		if (!content.includes(dirEntry)) {
			await fs.appendFile(
				gitignorePath,
				`\n# Auto-generated context docs\n${DOCS_DIR}/\n`,
				'utf-8'
			);
		}
	} catch {
		// No .gitignore — create one
		await fs.writeFile(
			gitignorePath,
			`# Auto-generated context docs\n${DOCS_DIR}/\n`,
			'utf-8'
		);
	}
}
